modules:
  - //cli/cli-core
  - //cli/cli-jvm
  - //cli/cli-linux
  - //cli/cli-test
  - //lib/spond
  - //lib/sportpress
  - //lib/test-resources
  - //lib/utils
  - //plugins/ktfmt
  - lib/runtime

plugins:
  - //plugins/ktfmt
