[versions]
kermit = "2.1.0"
kotlinx-coroutines = "1.11.0"
kotlinx-datetime = "0.8.0"
kotlinx-io = "0.9.1"
kotlinx-serialization = "1.11.0"
ktor = "3.5.2"
metro = "1.4.1"
test-balloon = "1.0.1-K2.4.0"

[libraries]
clikt = "com.github.ajalt.clikt:clikt:5.1.0"
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kermit-core = { module = "co.touchlab:kermit-core", version.ref = "kermit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-serialization-json-io = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-io", version.ref = "kotlinx-serialization" }
ksoup = "com.fleeksoft.ksoup:ksoup:0.2.6"
ktfmt = "com.facebook:ktfmt:0.64"
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-curl = { module = "io.ktor:ktor-client-curl", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-http = { module = "io.ktor:ktor-http", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
logback = "ch.qos.logback:logback-classic:1.6.1"
metro-compiler = { module = "dev.zacsweers.metro:compiler", version.ref = "metro" }
metro-runtime = { module = "dev.zacsweers.metro:runtime", version.ref = "metro" }
test-balloon-compiler = { module = "de.infix.testBalloon:testBalloon-compiler-plugin", version.ref = "test-balloon" }
test-balloon-runtime = { module = "de.infix.testBalloon:testBalloon-framework-core", version.ref = "test-balloon" }
javac = "com.google.errorprone:javac:9+181-r4173-1"

[plugins]
version-catalog-update = "nl.littlerobots.version-catalog-update:1.1.1"
